### ISSUE TITLE
Year 2021, 02 weeks Plan

### ISSUE THREAD

**Issue by fora22** [fora22/Study#4]
# Paper
## QR 알고리즘 ISDIC-MMSE
- [ ] 결론까지 작성하기
## 로봇팔 제어
- 해당사항 없음
___
# [Senior-Project](https://github.com/JEoN-Ha/Senior-Project) - [Plan](https://github.com/JEoN-Ha/Senior-Project/issues/71)
# First To Do
- [x] React-Router 문제에 대한 문제 설명 추가 #64 
- [x] '긴급' -> '중요' Labeling 적용에 관해 README 수정하고 다시 Review Request #65 
- [x] 공유 Reference Issue 발행 #72 

# Server To Do
- [x] `fetch()`를 통해 DB Insert, Update, Delete 테스트하기
- [ ] Swagger 를 활용한 Api Design
 
# 이미지 처리 To Do
## 자료조사하기
- [x] `Cloud 에서 Api를 통해 이미지 분류를 해주는 서비스` 찾기
- [x] 공유 Reference Issue 에 이미지 처리 관련 Reference 올리기
- [x] GCP Api 사용해보기
___
# [CodingTest](https://github.com/fora22/CodingTest) - [Plan](https://github.com/fora22/CodingTest/issues/57)
## 내용 정리
- [x] 정렬 알고리즘 4개(6장) 내용 작성해서 wiki에 올리기(예시 코드 포함)
- [x] 문자열에서 공백을 구분하여 `vector<string>` 으로 return 하는 함수 정리해서 wiki에 올리기
- [x] `ifstream` 객체를 통한 파일 입출력 내용 정리해서 wiki에 올리기
### 7장 이진 탐색(Binary Search)
- [x] 순차 탐색(Sequential Search) 구현
- [x] 이진 탐색(Binary Search), 이진 탐색 트리(Binary Search Tree) 내용 정리해서 wiki에 올리기
- [x] 실전문제 2번 부품 찾기
- [x] 실전문제 3번 떡볶이 떡 만들기

___
# [CreateBlog](https://github.com/fora22/CreateBlog)
## [Plan 1](https://github.com/fora22/CreateBlog/issues/11)
- [ ] 친구 블로그 페이지 하나 React로 구현하기
  - 인스타 같은 갤러리 형태
  - 추가적으로 사진을 클릭하면 화면 중간에 조그마한 창이 뜨면서 사진과 글이 올라오도록 구현
  - 이해를 돕기위한 사진은 나중에 추가하겠음
- [x] 간단한 블로그 구현(wiki 내용이 보여지는 페이지) - HTML, CSS, JS만 사용해서

## [Plan 2](https://github.com/fora22/CreateBlog/issues/15)
- [ ] Gatsby.js에 대해 조사하고 정리하여 GIthub wiki에 올리기
___
# [Socket 통신](https://github.com/fora22/cpp_Network)
- [ ] 기본적인 Socket 통신 만들기
  - [ ] Threading을 통해 Client -> Server and next Server -> Client
___
# [뉴스크롤러](https://github.com/fora22/NewsCrawler)
- 해당사항 없음
